plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
//    id 'org.spongepowered.mixin' version '0.7.+'   // Mixin Gradle 插件
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        url 'https://maven.blamejared.com'
    }
    maven {
        url 'https://maven.aliyun.com/repository/public'
    }
    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "dgh" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"


//
//    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:15.20.0.129")
//
//    compileOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84.1-FORGE:api")
//    runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84.1-FORGE")
//
//    compileOnly fg.deobf("curse.maven:timeless-and-classics-zero-1028108:7278003-sources-7278003")
//    runtimeOnly fg.deobf("curse.maven:timeless-and-classics-zero-1028108:7278003-sources-7278003")
//
//    compileOnly fg.deobf("curse.maven:touhou-little-maid-355044:7307720-sources-7307731")
//    runtimeOnly fg.deobf("curse.maven:touhou-little-maid-355044:7307720-sources-7307731")
//
//    // MixinExtras
//    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
//    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0")) {
//        jarJar.ranged(it, "[0.5.0,)")
//    }
//
//    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}


//
//mixin {
//    add sourceSets.main, 'dgh.refmap.json'
//    config 'dgh.mixins.json'
//    config 'dgh.TaZC.mixins.json'
//    config 'dgh.touhoulittlemaid.mixins.json'
//}
//
//
//runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:15.20.0.129")
//
//compileOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84.1-FABRIC")
//runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84.1-FABRIC")
//
//compileOnly fg.deobf("curse.maven:tacz-refabricated:1334246-sources-7408240")
//runtimeOnly fg.deobf("curse.maven:tacz-refabricated:1334246-sources-7408240")
//
//compileOnly fg.deobf("curse.maven:forge-config-api-port:547434-sources-7260491")
//runtimeOnly fg.deobf("curse.maven:forge-config-api-port:547434-sources-7260491")
//
//compileOnly fg.deobf("curse.maven:touhoulittlemaid-orihime:1311287-sources-7569327")
//runtimeOnly fg.deobf("curse.maven:touhoulittlemaid-orihime:1311287-sources-7569327")