plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
    id 'idea'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        url 'https://maven.blamejared.com'
    }
    maven {
        url 'https://maven.aliyun.com/repository/public'
    }
    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {// Forge Config API Port
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "dgh" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modImplementation "curse.maven:architectury-api-419699:5137936"

    runtimeOnly "curse.maven:jei-238222:7391694"

    compileOnly "curse.maven:patchouli-fabric-393236:6164574"
    runtimeOnly "curse.maven:patchouli-fabric-393236:6164574"

    runtimeOnly "curse.maven:forge-config-api-port-547434:7260491"
    compileOnly "curse.maven:tacz-refabricated-1334246:7408244"
    runtimeOnly "curse.maven:tacz-refabricated-1334246:7408240"

    compileOnly "curse.maven:touhoulittlemaid-orihime-1311287:7569333"
    runtimeOnly "curse.maven:touhoulittlemaid-orihime-1311287:7569327"

    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:8.0.2"

//     MixinExtras
//    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
//    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0")) {
//        jarJar.ranged(it, "[0.5.0,)")
//    }
//
//    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}